# ============================================================
# CONFIGURAÇÕES DO EXPERIMENTO
# ============================================================

# --- Parâmetros do Dataset ---
dataset:
  nome: "FLAME"               
  pasta_imagens: "datasets/flame-dataset-morph"  
  pasta_saida: "datasets/flame-dataset-morph/Detection" # Onde o modelo vai achar o dataset.yaml     
  train_size: 0.70
  val_size: 0.20
  test_size: 0.10

# --- Parâmetros de Processamento (Visão Computacional) ---
processamento:
  kernel_size: 11
  merge_margin: 60
  min_area_pct: 0.0001


# Aqui que alteramos o modelo usado, e em nome_experimento é o diretório que vai ficar salvo na pasta runs
treinamento:
  modelo_base: "pesos/yolov8n.pt"      
  epochs: 200                    
  imgsz: 640                     
  batch_size: 64
  nome_experimento: "flame-morph-200epochs-yolov8n-run"
  device: 0
  workers: 4